# ========================================================================
# ~/.bashrc: executed by bash(1) for non-login shells by design, actually
# invoked by my .profile scripts now so that I can keep my configurations
# contained. See /usr/share/doc/bash/examples/startup-files (in the package
# bash-doc) for examples.
# ========================================================================

# If not running interactively, don't do anything
[ -z "$PS1" ] && return
# Then see if we've got a ksh around somewhere
if [ $(echo $OSTYPE | grep -i solaris) ]
then
   [ \! -z "$(which ksh)" ] && exec ksh -i
else
   [ \! -z "$(which ksh)" ] && exec ksh -l
fi


# don't put duplicate lines in the history. See bash(1) for more options
HISTCONTROL=ignoredups
export HISTCONTROL

# cdspell:  If set, minor errors in the spelling of a directory component in a
#           cd command will be corrected. The errors checked for are transposed
#           characters, a missing character, and one character too many. If a
#           correction is found, the corrected file name is printed, and the
#           command proceeds.  This option is only used by interactive shells.
#
# cmdhist:  If set, bash attempts to save all lines of a multiple-line command
#           in the same history entry. This allows easy re-editing of multi-line
#           commands.
#
# dotglob:  If set, bash includes filenames beginning with a ‘.’ in the results
#           of pathname expansion.
#
# extglob:  If set, the extended pattern matching features described
#           above under Pathname Expansion are enabled.
#
# checkwinsize:   If set, bash checks the window size after each command and, if
#                 necessary, updates the values of LINES and COLUMNS.
shopt -s checkwinsize cdspell cmdhist dotglob extglob

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color)
    PS1='\[\033[01;32m\]\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]:'
    ;;
*)
    PS1='\[\033[04m\]\h \w\[\033[00m\]: '
    ;;
esac

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    export PROMPT_COMMAND
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# And set up the one true command-line editing style
set -o vi

# Finally, if we have a bash functions file, source it.
if [ -f ${HOME}/.fns.bash ]
then
   . ${HOME}/.fns.bash
fi

# vim: tw=78 ts=3 sw=3 et nowrap ft=sh
